### PR TITLE
Update PayoutRoutes.swift

### PR DESCRIPTION
**Pull request by Maxim-Inv**
Make public methods

### CODE REVIEW

**Comment by Andrewangeta** [comment]
@Maxim-Inv any reason why the status checks don’t run? Maybe try re opening a PR.

**Comment by Maxim-Inv** [comment]
Idk. Should I close this PR and create a new one?

**Comment by Andrewangeta** [comment]
Yea I’d probably do that to see if it corrects itself.

**Comment by Andrewangeta** [comment]
Also make sure you have the latest master pulled in (which I think you do anyway)

**Comment by Maxim-Inv** [comment]
Yes, I have the latest

**Pull request closed without merging**
